
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: iwashita
  password: jlkjjklj
  host: localhost

development:
  <<: *default
  database: development


test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
